### ISSUE TITLE
Revive usecase `common_neighbor_2`

### ISSUE THREAD

**Issue by arsenius7** [BlueBrain/MOOC-hippocampus-network-simulation-2019#11]
`common_neighbor_2` is currently not operational (out of memory error).
Most likely it has something to do with NRN -> SONATA migration; we'll need to clarify the intent of the usecase using some previously working configuration, and fix the current notebook code accordingly.

**Comment by antonelepfl** [comment]
You can find an old working version on [Collab](https://collab.humanbrainproject.eu/#/collab/33645/nav/307534) before even sonata not sure if it's very useful though

**Comment by tomdele** [comment]
A fix is available [https://github.com/BlueBrain/MOOC-hippocampus-network-simulation-2019/pull/14](url)

The problem was due to the `efferent_con_mat` free function. Inside this function, an adjacency matrix was created using a wrong shape = `nb_node_in_pop x nb_edges_in_circuit` instead of  `nb_node_in_pop x nb_nodes_in_circuit`.
